### ISSUE TITLE
Request for an at least minimal documentation

### ISSUE THREAD

**Issue by eschlot** [adospace/litedbpad#7]
Hello,

I use LiteDB for quiet some time and found LINQPad only now. I downloaded V6 and the plugin from here and can establish a data base connection. But the usage is completely unclear to me. The only documentation/howto is the one line in the Readme.md: 

< mycollectionname >.FindAll()

But what the "mycollectionname"
 is is undocumented. At least for my database the collection names visible in LiteDB explorer do not work and are unknown. Also in LINQPad the database tables are not shown when the database is connected. It says "populating" and closes again. I cannot even understand if this is the expected behavior because it is not clear what it should be. 

![Anmerkung 2019-12-28 162844](https://user-images.githubusercontent.com/8495699/71545771-2d94a580-298f-11ea-99ec-bef13b67bc43.png)

![Anmerkung 2019-12-28 163034](https://user-images.githubusercontent.com/8495699/71545789-66347f00-298f-11ea-8345-e41b2ce5abf0.png)

Do I have to include my classes in the LINQPad?

It would be cool to have some more info on the overall usage and functionality because the combination of LINQPad and LiteDB seems to be promising. I would also support in generation of documentation or reviewing. 
Thank You.

**Comment by adospace** [comment]
LinqPad V6 is based on .NET core, so you can't use the driver lpx you find here because is compiled against full .net (you can use it in linqpad v5 instead and mycollectionname is the name of the collection as reported when you expand the connection tree node).
I'm working to v6 of the driver but it's not yet ready.
Lastly, I agree with you, documentation requires some improvements :)

**Comment by eschlot** [comment]
**Thank you very much** for this explanation. This helped me already to find some way forward for me.
